### PR TITLE
Use latest pod resource changes

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Review by ffromani — COMMENTED** [review]
/lgtm

**Comment by swatisehgal** [comment]
I tested this PR on a 2 node kind cluster (master +worker)  with sample device plugin [here](https://github.com/swatisehgal/sample-device-plugin/tree/nfd-rte) (deviceA config: [here](https://github.com/swatisehgal/sample-device-plugin/blob/master/config/device_A.json) and deviceB config: [here](https://github.com/swatisehgal/sample-device-plugin/blob/master/config/device_B.json)) and two sample pods ([here](https://github.com/swatisehgal/sample-device-plugin/tree/nfd-rte/manifests/sample-pods)) running in the rte namespace consuming resources from the master node (Pod1 consuming 2 cpus, 2 deviceA, 2 deviceB from numanode0 and Pod1 consuming 2 cpus, 2 deviceA and 2 deviceB from numanode1).CRDs are getting creating but accounting is not happening correctly in case of devices, cpu accounting is correct. From the point of view of changes you have proposed, the PR looks good which leads me to believe that this might have been caused due to some changes in the latest pod resource API that we are using now. We will need to deep dive into that to narrow down the issue. Could you recreate the environment with sample device plugin (nfd-rte branch) and verify my observation and we can try debug from there

**Comment by cynepco3hahue** [comment]
> I tested this PR on a 2 node kind cluster (master +worker) with sample device plugin [here](https://github.com/swatisehgal/sample-device-plugin/tree/nfd-rte) (deviceA config: [here](https://github.com/swatisehgal/sample-device-plugin/blob/master/config/device_A.json) and deviceB config: [here](https://github.com/swatisehgal/sample-device-plugin/blob/master/config/device_B.json)) and two sample pods ([here](https://github.com/swatisehgal/sample-device-plugin/tree/nfd-rte/manifests/sample-pods)) running in the rte namespace consuming resources from the master node (Pod1 consuming 2 cpus, 2 deviceA, 2 deviceB from numanode0 and Pod1 consuming 2 cpus, 2 deviceA and 2 deviceB from numanode1).CRDs are getting creating but accounting is not happening correctly in case of devices, cpu accounting is correct. From the point of view of changes you have proposed, the PR looks good which leads me to believe that this might have been caused due to some changes in the latest pod resource API that we are using now. We will need to deep dive into that to narrow down the issue. Could you recreate the environment with sample device plugin (nfd-rte branch) and verify my observation and we can try debug from there

The problem that currently I do not have a multi-NUMA machine, can we debug it under your environment? Also probably @fromanirh can provide better help with it because I do not really familiar with the pod resource API code.

**Comment by ffromani** [comment]
I think the real issue here is that we need to stop and set some CI to be able to catch regressions.

**Comment by cynepco3hahue** [comment]
> I think the real issue here is that we need to stop and set some CI to be able to catch regressions.

IMHO firstly we should align the NFD repo with the latest pod resource API changes and after fix all issues, I do not see a point to create a CI to the old implementation of the pod resource API when it will not work once you have a kubelet with the latest changes. By CI do you mean d/s CI?

**Comment by swatisehgal** [comment]
@cynepco3hahue Sure I can share my environment. Totally valid point by @fromanirh highlighting the importance of CI for regression testing but we should get this PR merged first to make sure we have this working with the latest implementation of podresource API, that way for our CI we are in a position to test it on a cluster with the most upto date podresource API changes.

**Pull request merged**
